-- 1. CREATION DES UTILISATEURS 
-- On crée un utilisateur par métier pour tester
CREATE USER U_DIRECTEUR IDENTIFIED BY pass123;  -- Pour la Capitainerie
CREATE USER U_CHEF_OPS  IDENTIFIED BY pass123;  -- Pour les Opérations
CREATE USER U_RH        IDENTIFIED BY pass123;  -- Pour les RH
CREATE USER U_COMPTABLE IDENTIFIED BY pass123;  -- Pour la Finance

-- On leur donne le droit de se connecter
GRANT CREATE SESSION TO U_DIRECTEUR, U_CHEF_OPS, U_RH, U_COMPTABLE;

-- 2. EXÉCUTION DES SCRIPTS DE RÔLES

-- 3. ATTRIBUTION DES RÔLES AUX UTILISATEURS
GRANT ROLE_CAPITAINERIE TO U_DIRECTEUR;
GRANT ROLE_OPERATIONS   TO U_CHEF_OPS;
GRANT ROLE_RH           TO U_RH;
GRANT ROLE_FINANCE      TO U_COMPTABLE;

-- Donner des quotas sur le tablespace pour qu'ils puissent insérer (si besoin)
ALTER USER U_DIRECTEUR QUOTA UNLIMITED ON USERS;
ALTER USER U_CHEF_OPS  QUOTA UNLIMITED ON USERS;
ALTER USER U_RH        QUOTA UNLIMITED ON USERS;
ALTER USER U_COMPTABLE QUOTA UNLIMITED ON USERS;