
--  DDL for Table AFFECTATION
--------------------------------------------------------

  CREATE TABLE "AFFECTATION" 
   (	"HEURES_TRAVAILLEES" FLOAT(24), 
	"DATE_AFFECTATION" TIMESTAMP (6), 
	"ID_EMPLOYE" NUMBER(19,0), 
	"ID_OPERATION" NUMBER(19,0), 
	"ROLE" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table BILLET
--------------------------------------------------------

  CREATE TABLE "BILLET" 
   (	"PRIX" NUMBER(38,2), 
	"DATE_VOYAGE" TIMESTAMP (6), 
	"ID_BILLET" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_NAVIRE" NUMBER(19,0), 
	"ID_PASSAGER" NUMBER(19,0), 
	"NUM_CABINE" VARCHAR2(255 CHAR), 
	"NUM_TICKET" VARCHAR2(255 CHAR), 
	"TYPE_CLASSE" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table CARGAISON
--------------------------------------------------------

  CREATE TABLE "CARGAISON" 
   (	"EST_DANGEREUX" NUMBER(1,0), 
	"POIDS_TOTAL" FLOAT(24), 
	"ID_CARGAISON" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_NAVIRE" NUMBER(19,0), 
	"LIBELLE" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table CONTENEUR
--------------------------------------------------------

  CREATE TABLE "CONTENEUR" 
   (	"EST_REFRIGERE" NUMBER(1,0), 
	"TAILLE_PIEDS" NUMBER(10,0), 
	"ID_CARGAISON" NUMBER(19,0), 
	"ID_CONTENEUR" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TYPE_CONTENEUR" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "EMPLOYE" 
   (	"DATE_EMBAUCHE" DATE, 
	"TAUX_HORAIRE" NUMBER(38,2), 
	"ID_EMPLOYE" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_SUPERIEUR" NUMBER(19,0), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"MATRICULE" VARCHAR2(255 CHAR), 
	"NOM" VARCHAR2(255 CHAR), 
	"POSTE" VARCHAR2(255 CHAR), 
	"PRENOM" VARCHAR2(255 CHAR), 
	"STATUT" VARCHAR2(255 CHAR), 
	"TELEPHONE" VARCHAR2(255 CHAR),
    "PASSWORD" VARCHAR2(255 CHAR), 
    "ROLE_SYSTEME" VARCHAR2(50 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table ESCALE
--------------------------------------------------------

  CREATE TABLE "ESCALE" 
   (	"TIRANT_EAU_ENTREE" FLOAT(24), 
	"TIRANT_EAU_SORTIE" FLOAT(24), 
	"DATE_ARRIVEE_PREVUE" TIMESTAMP (6), 
	"DATE_ARRIVEE_REELLE" TIMESTAMP (6), 
	"DATE_DEPART_PREVUE" TIMESTAMP (6), 
	"DATE_DEPART_REELLE" TIMESTAMP (6), 
	"ID_ESCALE" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_NAVIRE" NUMBER(19,0), 
	"ID_QUAI" NUMBER(19,0), 
	"ID_RESERVATION" NUMBER(19,0), 
	"NUM_REFERENCE" VARCHAR2(255 CHAR), 
	"STATUT_ESCALE" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table FACTURE
--------------------------------------------------------

  CREATE TABLE "FACTURE" 
   (	"MONTANT_TOTAL" NUMBER(38,2), 
	"DATE_ECHEANCE" TIMESTAMP (6), 
	"DATE_EMISSION" TIMESTAMP (6), 
	"ID_ESCALE" NUMBER(19,0), 
	"ID_FACTURE" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STATUT_PAIEMENT" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table FREQUENTATION_ZONE
--------------------------------------------------------

  CREATE TABLE "FREQUENTATION_ZONE" 
   (	"NAVIRE_PECHE_ID_NAVIRE" NUMBER(19,0), 
	"ZONES_ID_ZONE" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NAVIRE
--------------------------------------------------------

  CREATE TABLE "NAVIRE" 
   (	"LONGUEUR" FLOAT(24), 
	"TIRANT_EAU" FLOAT(24), 
	"ID_NAVIRE" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOM" VARCHAR2(255 CHAR), 
	"NUM_IMO" VARCHAR2(255 CHAR), 
	"PAVILLON" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table NAVIRE_COMMERCE
--------------------------------------------------------

  CREATE TABLE "NAVIRE_COMMERCE" 
   (	"CAPACITE_CONTENEURS" NUMBER(10,0), 
	"TONNAGE_MAX" FLOAT(24), 
	"ID_NAVIRE" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NAVIRE_PASSAGER
--------------------------------------------------------

  CREATE TABLE "NAVIRE_PASSAGER" 
   (	"CAPACITE_PASSAGERS" NUMBER(10,0), 
	"NB_CABINES" NUMBER(10,0), 
	"ID_NAVIRE" NUMBER(19,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NAVIRE_PECHE
--------------------------------------------------------

  CREATE TABLE "NAVIRE_PECHE" 
   (	"CAPACITE_STOCKAGE" FLOAT(24), 
	"ID_NAVIRE" NUMBER(19,0), 
	"TYPE_PECHE" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table OPERATION
--------------------------------------------------------

  CREATE TABLE "OPERATION" 
   (	"COUT_MATERIEL" NUMBER(38,2), 
	"DATE_OPERATION" TIMESTAMP (6), 
	"ID_CARGAISON" NUMBER(19,0), 
	"ID_ESCALE" NUMBER(19,0), 
	"ID_OPERATION" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LIBELLE" VARCHAR2(255 CHAR), 
	"TYPE_OPERATION" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table PASSAGER
--------------------------------------------------------

  CREATE TABLE "PASSAGER" 
   (	"ID_PASSAGER" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMAIL" VARCHAR2(255 CHAR), 
	"NATIONALITE" VARCHAR2(255 CHAR), 
	"NOM" VARCHAR2(255 CHAR), 
	"NUM_PASSEPORT" VARCHAR2(255 CHAR), 
	"PRENOM" VARCHAR2(255 CHAR), 
	"TELEPHONE" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table QUAI
--------------------------------------------------------

  CREATE TABLE "QUAI" 
   (	"CAPACITE_TONNAGE" FLOAT(24), 
	"LONGUEUR_MAX" FLOAT(24), 
	"PROFONDEUR_BASSIN" FLOAT(24), 
	"ID_QUAI" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOM" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "RESERVATION" 
   (	"DATE_DEBUT_SOUHAITEE" TIMESTAMP (6), 
	"DATE_DEMANDE" TIMESTAMP (6), 
	"DATE_FIN_SOUHAITEE" TIMESTAMP (6), 
	"ID_NAVIRE" NUMBER(19,0), 
	"ID_RESERVATION" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MOTIF" VARCHAR2(255 CHAR), 
	"PRIORITE" VARCHAR2(255 CHAR), 
	"STATUT" VARCHAR2(255 CHAR)
   ) ;
--------------------------------------------------------
--  DDL for Table ZONE_PECHE
--------------------------------------------------------

  CREATE TABLE "ZONE_PECHE" 
   (	"ID_ZONE" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"COORDONNEES_GEO" VARCHAR2(255 CHAR), 
	"NOM" VARCHAR2(255 CHAR)
   ) ;
REM INSERTING into AFFECTATION
SET DEFINE OFF;
REM INSERTING into BILLET
SET DEFINE OFF;
REM INSERTING into CARGAISON
SET DEFINE OFF;
REM INSERTING into CONTENEUR
SET DEFINE OFF;
REM INSERTING into EMPLOYE
SET DEFINE OFF;
REM INSERTING into ESCALE
SET DEFINE OFF;
REM INSERTING into FACTURE
SET DEFINE OFF;
REM INSERTING into FREQUENTATION_ZONE
SET DEFINE OFF;
REM INSERTING into NAVIRE
SET DEFINE OFF;
REM INSERTING into NAVIRE_COMMERCE
SET DEFINE OFF;
REM INSERTING into NAVIRE_PASSAGER
SET DEFINE OFF;
REM INSERTING into NAVIRE_PECHE
SET DEFINE OFF;
REM INSERTING into OPERATION
SET DEFINE OFF;
REM INSERTING into PASSAGER
SET DEFINE OFF;
REM INSERTING into QUAI
SET DEFINE OFF;
REM INSERTING into RESERVATION
SET DEFINE OFF;
REM INSERTING into ZONE_PECHE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008464
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008464" ON "AFFECTATION" ("ID_EMPLOYE", "ID_OPERATION") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008466
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008466" ON "BILLET" ("ID_BILLET") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008467
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008467" ON "BILLET" ("NUM_TICKET") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008470
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008470" ON "CARGAISON" ("ID_CARGAISON") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008473
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008473" ON "CONTENEUR" ("ID_CONTENEUR") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008475
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008475" ON "EMPLOYE" ("ID_EMPLOYE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008476
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008476" ON "EMPLOYE" ("MATRICULE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008478
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008478" ON "ESCALE" ("ID_ESCALE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008479
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008479" ON "ESCALE" ("ID_RESERVATION") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008480
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008480" ON "ESCALE" ("NUM_REFERENCE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008482
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008482" ON "FACTURE" ("ID_FACTURE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008486
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008486" ON "NAVIRE" ("ID_NAVIRE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008487
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008487" ON "NAVIRE" ("NUM_IMO") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008489
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008489" ON "NAVIRE_COMMERCE" ("ID_NAVIRE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008491
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008491" ON "NAVIRE_PASSAGER" ("ID_NAVIRE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008493
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008493" ON "NAVIRE_PECHE" ("ID_NAVIRE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008495
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008495" ON "OPERATION" ("ID_OPERATION") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008497
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008497" ON "PASSAGER" ("ID_PASSAGER") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008498
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008498" ON "PASSAGER" ("NUM_PASSEPORT") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008500
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008500" ON "QUAI" ("ID_QUAI") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008502
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008502" ON "RESERVATION" ("ID_RESERVATION") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008504
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008504" ON "ZONE_PECHE" ("ID_ZONE") 
  ;
--------------------------------------------------------
--  Constraints for Table AFFECTATION
--------------------------------------------------------

  ALTER TABLE "AFFECTATION" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "AFFECTATION" MODIFY ("ID_OPERATION" NOT NULL ENABLE);
  ALTER TABLE "AFFECTATION" ADD PRIMARY KEY ("ID_EMPLOYE", "ID_OPERATION")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table BILLET
--------------------------------------------------------

  ALTER TABLE "BILLET" MODIFY ("ID_BILLET" NOT NULL ENABLE);
  ALTER TABLE "BILLET" ADD PRIMARY KEY ("ID_BILLET")
  USING INDEX  ENABLE;
  ALTER TABLE "BILLET" ADD UNIQUE ("NUM_TICKET")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CARGAISON
--------------------------------------------------------

  ALTER TABLE "CARGAISON" MODIFY ("ID_CARGAISON" NOT NULL ENABLE);
  ALTER TABLE "CARGAISON" ADD CHECK (est_dangereux in (0,1)) ENABLE;
  ALTER TABLE "CARGAISON" ADD PRIMARY KEY ("ID_CARGAISON")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTENEUR
--------------------------------------------------------

  ALTER TABLE "CONTENEUR" MODIFY ("ID_CONTENEUR" NOT NULL ENABLE);
  ALTER TABLE "CONTENEUR" ADD CHECK (est_refrigere in (0,1)) ENABLE;
  ALTER TABLE "CONTENEUR" ADD PRIMARY KEY ("ID_CONTENEUR")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "EMPLOYE" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYE" ADD PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX  ENABLE;
  ALTER TABLE "EMPLOYE" ADD UNIQUE ("MATRICULE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESCALE
--------------------------------------------------------

  ALTER TABLE "ESCALE" MODIFY ("ID_ESCALE" NOT NULL ENABLE);
  ALTER TABLE "ESCALE" ADD PRIMARY KEY ("ID_ESCALE")
  USING INDEX  ENABLE;
  ALTER TABLE "ESCALE" ADD UNIQUE ("ID_RESERVATION")
  USING INDEX  ENABLE;
  ALTER TABLE "ESCALE" ADD UNIQUE ("NUM_REFERENCE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "FACTURE" MODIFY ("ID_FACTURE" NOT NULL ENABLE);
  ALTER TABLE "FACTURE" ADD PRIMARY KEY ("ID_FACTURE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table FREQUENTATION_ZONE
--------------------------------------------------------

  ALTER TABLE "FREQUENTATION_ZONE" MODIFY ("NAVIRE_PECHE_ID_NAVIRE" NOT NULL ENABLE);
  ALTER TABLE "FREQUENTATION_ZONE" MODIFY ("ZONES_ID_ZONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NAVIRE
--------------------------------------------------------

  ALTER TABLE "NAVIRE" MODIFY ("ID_NAVIRE" NOT NULL ENABLE);
  ALTER TABLE "NAVIRE" ADD PRIMARY KEY ("ID_NAVIRE")
  USING INDEX  ENABLE;
  ALTER TABLE "NAVIRE" ADD UNIQUE ("NUM_IMO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table NAVIRE_COMMERCE
--------------------------------------------------------

  ALTER TABLE "NAVIRE_COMMERCE" MODIFY ("ID_NAVIRE" NOT NULL ENABLE);
  ALTER TABLE "NAVIRE_COMMERCE" ADD PRIMARY KEY ("ID_NAVIRE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table NAVIRE_PASSAGER
--------------------------------------------------------

  ALTER TABLE "NAVIRE_PASSAGER" MODIFY ("ID_NAVIRE" NOT NULL ENABLE);
  ALTER TABLE "NAVIRE_PASSAGER" ADD PRIMARY KEY ("ID_NAVIRE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table NAVIRE_PECHE
--------------------------------------------------------

  ALTER TABLE "NAVIRE_PECHE" MODIFY ("ID_NAVIRE" NOT NULL ENABLE);
  ALTER TABLE "NAVIRE_PECHE" ADD PRIMARY KEY ("ID_NAVIRE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table OPERATION
--------------------------------------------------------

  ALTER TABLE "OPERATION" MODIFY ("ID_OPERATION" NOT NULL ENABLE);
  ALTER TABLE "OPERATION" ADD PRIMARY KEY ("ID_OPERATION")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table PASSAGER
--------------------------------------------------------

  ALTER TABLE "PASSAGER" MODIFY ("ID_PASSAGER" NOT NULL ENABLE);
  ALTER TABLE "PASSAGER" ADD PRIMARY KEY ("ID_PASSAGER")
  USING INDEX  ENABLE;
  ALTER TABLE "PASSAGER" ADD UNIQUE ("NUM_PASSEPORT")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUAI
--------------------------------------------------------

  ALTER TABLE "QUAI" MODIFY ("ID_QUAI" NOT NULL ENABLE);
  ALTER TABLE "QUAI" ADD PRIMARY KEY ("ID_QUAI")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "RESERVATION" MODIFY ("ID_RESERVATION" NOT NULL ENABLE);
  ALTER TABLE "RESERVATION" ADD PRIMARY KEY ("ID_RESERVATION")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZONE_PECHE
--------------------------------------------------------

  ALTER TABLE "ZONE_PECHE" MODIFY ("ID_ZONE" NOT NULL ENABLE);
  ALTER TABLE "ZONE_PECHE" ADD PRIMARY KEY ("ID_ZONE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AFFECTATION
--------------------------------------------------------

  ALTER TABLE "AFFECTATION" ADD CONSTRAINT "FKMA3Y33WTTX6PMCQVSX4YCY196" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "EMPLOYE" ("ID_EMPLOYE") ENABLE;
  ALTER TABLE "AFFECTATION" ADD CONSTRAINT "FKCIE42IVRN3TLIKG7VIJBWSFLT" FOREIGN KEY ("ID_OPERATION")
	  REFERENCES "OPERATION" ("ID_OPERATION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BILLET
--------------------------------------------------------

  ALTER TABLE "BILLET" ADD CONSTRAINT "FKTCAG9K2NXQCQ3VLHR0YILQMC9" FOREIGN KEY ("ID_NAVIRE")
	  REFERENCES "NAVIRE" ("ID_NAVIRE") ENABLE;
  ALTER TABLE "BILLET" ADD CONSTRAINT "FK7CIIEMCAM8Y7VLJFW4J9497Q5" FOREIGN KEY ("ID_PASSAGER")
	  REFERENCES "PASSAGER" ("ID_PASSAGER") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CARGAISON
--------------------------------------------------------

  ALTER TABLE "CARGAISON" ADD CONSTRAINT "FK14T770QWIJGI07CTEVCKLWG1I" FOREIGN KEY ("ID_NAVIRE")
	  REFERENCES "NAVIRE_COMMERCE" ("ID_NAVIRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTENEUR
--------------------------------------------------------

  ALTER TABLE "CONTENEUR" ADD CONSTRAINT "FKET6JCW8W2RDFTDWH4KCOFTG13" FOREIGN KEY ("ID_CARGAISON")
	  REFERENCES "CARGAISON" ("ID_CARGAISON") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "EMPLOYE" ADD CONSTRAINT "FKA9UDSRHAS7BY5QEFTUIF45RCB" FOREIGN KEY ("ID_SUPERIEUR")
	  REFERENCES "EMPLOYE" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESCALE
--------------------------------------------------------

  ALTER TABLE "ESCALE" ADD CONSTRAINT "FKH7Y1A2C6LPV949QLAK74OP6C7" FOREIGN KEY ("ID_NAVIRE")
	  REFERENCES "NAVIRE" ("ID_NAVIRE") ENABLE;
  ALTER TABLE "ESCALE" ADD CONSTRAINT "FKNUMPPB9DLVEA7R2JX701M207W" FOREIGN KEY ("ID_QUAI")
	  REFERENCES "QUAI" ("ID_QUAI") ENABLE;
  ALTER TABLE "ESCALE" ADD CONSTRAINT "FKHX9NRKYOM9XB5MED7BD6PDIHH" FOREIGN KEY ("ID_RESERVATION")
	  REFERENCES "RESERVATION" ("ID_RESERVATION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "FACTURE" ADD CONSTRAINT "FK91JSN0QT0K8OKLASYBJ3AEOBS" FOREIGN KEY ("ID_ESCALE")
	  REFERENCES "ESCALE" ("ID_ESCALE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FREQUENTATION_ZONE
--------------------------------------------------------

  ALTER TABLE "FREQUENTATION_ZONE" ADD CONSTRAINT "FKDU6MHEFCMQJVTLOVJ7IXHH1L" FOREIGN KEY ("ZONES_ID_ZONE")
	  REFERENCES "ZONE_PECHE" ("ID_ZONE") ENABLE;
  ALTER TABLE "FREQUENTATION_ZONE" ADD CONSTRAINT "FK9NL86NFDHA2SGNXAEULJL3MWP" FOREIGN KEY ("NAVIRE_PECHE_ID_NAVIRE")
	  REFERENCES "NAVIRE_PECHE" ("ID_NAVIRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NAVIRE_COMMERCE
--------------------------------------------------------

  ALTER TABLE "NAVIRE_COMMERCE" ADD CONSTRAINT "FK6SH0DUQDU4JREPSXI1BER95W3" FOREIGN KEY ("ID_NAVIRE")
	  REFERENCES "NAVIRE" ("ID_NAVIRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NAVIRE_PASSAGER
--------------------------------------------------------

  ALTER TABLE "NAVIRE_PASSAGER" ADD CONSTRAINT "FKPM7L7G4VJILXM3D9134C6R587" FOREIGN KEY ("ID_NAVIRE")
	  REFERENCES "NAVIRE" ("ID_NAVIRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NAVIRE_PECHE
--------------------------------------------------------

  ALTER TABLE "NAVIRE_PECHE" ADD CONSTRAINT "FKIRKHBAQNVGAV53AE1C8RD8LG9" FOREIGN KEY ("ID_NAVIRE")
	  REFERENCES "NAVIRE" ("ID_NAVIRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OPERATION
--------------------------------------------------------

  ALTER TABLE "OPERATION" ADD CONSTRAINT "FKMK9E3UGJIRNRMRJMQ649J9P1N" FOREIGN KEY ("ID_CARGAISON")
	  REFERENCES "CARGAISON" ("ID_CARGAISON") ENABLE;
  ALTER TABLE "OPERATION" ADD CONSTRAINT "FK6EGTKVQ8DGPAS11EVK8CO8RJQ" FOREIGN KEY ("ID_ESCALE")
	  REFERENCES "ESCALE" ("ID_ESCALE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK7LL42PR0DVHMVJFO7UFBEKCHP" FOREIGN KEY ("ID_NAVIRE")
	  REFERENCES "NAVIRE" ("ID_NAVIRE") ENABLE;
