-- À EXÉCUTER EN TANT QUE ADMIN (SYSTEM)

-- 1. Synonymes pour les Tables et Vues
CREATE OR REPLACE PUBLIC SYNONYM V_EMPLOYE_OPS FOR SYSTEM.V_EMPLOYE_OPS;
CREATE OR REPLACE PUBLIC SYNONYM V_EMPLOYE_FINANCE FOR SYSTEM.V_EMPLOYE_FINANCE;
CREATE OR REPLACE PUBLIC SYNONYM V_PAIE_AFFECTATION FOR SYSTEM.V_PAIE_AFFECTATION;
-- Ajout des autres tables nécessaires aux utilisateurs
CREATE OR REPLACE PUBLIC SYNONYM EMPLOYE FOR SYSTEM.EMPLOYE;
CREATE OR REPLACE PUBLIC SYNONYM ESCALE FOR SYSTEM.ESCALE;
CREATE OR REPLACE PUBLIC SYNONYM OPERATION FOR SYSTEM.OPERATION;
CREATE OR REPLACE PUBLIC SYNONYM NAVIRE FOR SYSTEM.NAVIRE;
CREATE OR REPLACE PUBLIC SYNONYM QUAI FOR SYSTEM.QUAI;
CREATE OR REPLACE PUBLIC SYNONYM AFFECTATION FOR SYSTEM.AFFECTATION;
CREATE OR REPLACE PUBLIC SYNONYM FACTURE FOR SYSTEM.FACTURE;
CREATE OR REPLACE PUBLIC SYNONYM RESERVATION FOR SYSTEM.RESERVATION;

-- 2. Synonymes pour les Packages (Crucial pour vos tests)
CREATE OR REPLACE PUBLIC SYNONYM PKG_OPERATIONS FOR SYSTEM.PKG_OPERATIONS;
CREATE OR REPLACE PUBLIC SYNONYM PKG_RH FOR SYSTEM.PKG_RH;
CREATE OR REPLACE PUBLIC SYNONYM PKG_FINANCE FOR SYSTEM.PKG_FINANCE;
CREATE OR REPLACE PUBLIC SYNONYM PKG_MANAGER_QUAI FOR SYSTEM.PKG_MANAGER_QUAI;

-- 3. Confirmation
COMMIT;